### ISSUE TITLE
Widget only shows No such file or directory

### ISSUE THREAD

**Issue by JoanComasFdz** [pauloamgomes/ubersicht-docker-containers#2]
* macOS High Sierra version 10.13.6.
* Ubersicht v 1.3 (56).

I downloaded the zip file, extract the folder and copied the folder to the widgets folder of uberischt. The widget only shows No such file or directory:

![docker container widgets](https://user-images.githubusercontent.com/1288587/52479594-72fa8980-2ba9-11e9-9349-36cd3e8190a7.png)

The path usr/local/bin exists and contains a docker folder.
Running the command `docker ps --format "table {{.ID}}|{{.Names}}|{{.Size}}|{{.Status}}" | grep -v CONTAINER` on terminal works.
Running the command `osascript -e 'tell application "Terminal" to do script "docker exec -it '$1' sh"'`  on terminal works.

**Comment by JoanComasFdz** [comment]
I fixed it by adding the folder name to the `command` in the `index.coffee` script:

`command: "ubersicht-docker-containers-master/helper.sh getStatus"`

**Comment by pauloamgomes** [comment]
Hi @JoanComasFdz ,  that is not required, the script works well if you follow the installation steps:

"To enable, place the dockercontainers.widget folder in your Übersicht/widgets directory."

If you download the zip from the latest releases page https://github.com/pauloamgomes/ubersicht-docker-containers/releases and extract the folder will have the correct name
